# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56109bb4abdbc8a93ccdeb2adc90b63c86cce3273f2aceb38f536d2e9ae20c14351766f52e6cd22a18c6fa77244bef96941d6326256853fb11ec80dbd53d1559

test:
  secret_key_base: 6b0fea667cf0d046f6dd85d210b70e79b7bb8e103824b59938699a9f496558b9b54dd8ec94aa545ea1ea9ce4b0a01dc4d35d386559726f352cf6b165d886d843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
